### ISSUE TITLE
Let's Fix PayPal

### ISSUE THREAD

**Issue by jamcat22** [2factorauth/twofactorauth#1026]
Get ready for the longest description of an issue yet. There are currently about 14 issues/PRs related to PayPal. Let's face it, their 2FA is broken. It's inconsistent, it's not user-friendly, there aren't adequate docs, and there are many loopholes (but I will give them a chance to fix them first). Let's fix it!
# Todo

(A bullet point means in progress.)
- [x] Determine country compatibility. (See #1073.)
- [x] Fix compatibility matrix on main page. (See #1074.)
- [x] Determine compatibility with desktop account page.
- [x] Determine compatibility with desktop checkout.
- [x] Determine compatibility with mobile account page.
- [x] Determine compatibility with mobile checkout.
- [ ] Determine compatibility with physical store checkout.
- [x] Determine compatibility with iOS apps.
- Determine compatibility with iOS APIs.
- Determine compatibility with Android apps.
- Determine compatibility with Android APIs.
- [x] Determine compatibility with Windows Phone app(s).
- [x] Determine compatibility with Windows 8/8.1/10 app(s).
- [ ] Redo exceptions and add more information on the main page.
- [ ] Write new doc page using information gathered and include instructions on how to use and activate 2FA for PayPal.
# Key
- [ ] Login=Can you even login with any 2FA enabled?
- [ ] SMS=Can you use SMS 2FA?
- [ ] Software/Hardware=Can you use Software/Hardware 2FA?

A dash through a property indicates that it is not applicable.
A question mark next to a property means the status is unknown.
A bullet point means the status depends on certain conditions.
When applicable, a screenshot will be provided below or next to the property.
# Status
### Account Page
- [x] Login
- [x] SMS
  ![smsyes](https://cloud.githubusercontent.com/assets/1897053/10724464/640e45b0-7b8a-11e5-99d4-81259e993c27.png)
- [x] Software/Hardware
  ![shyes](https://cloud.githubusercontent.com/assets/1897053/10724466/67db1a7e-7b8a-11e5-8a5e-2b88b09e9ad3.png)
### Checkout
- [x] Login
- [x] SMS
- [x] Software/Hardware
### Responsive Account Page

This is the new design. It is the same as the desktop account page (with the option to login with phone number and PIN added), and therefore inherits its login compatibility.
### Responsive Checkout

This is the new design. It is the same as the desktop checkout, and therefore inherits its login compatibility.
### Old Checkout (Typically used for donations.)
- Login - This depends on whether you're logging in with a PIN code or a password. Software/Hardware is allowed when logging in with a password.
  ![loginno](https://cloud.githubusercontent.com/assets/1897053/10724843/27d36d52-7b8d-11e5-81de-231f91acf863.png)
- [ ] SMS
- [x] Software/Hardware
  ![shyes](https://cloud.githubusercontent.com/assets/1897053/6768392/050625d6-d02e-11e4-866a-3dc69e354b62.png)
### POS System (PIN Pad)

? Login
? SMS
? Software/Hardware
### PayPal App Check In

This is inherited from the main PayPal app on whichever device you use.
### Main App
- [x] Login
- [x] SMS
  ![smsyes](https://cloud.githubusercontent.com/assets/1897053/6768423/0fa54204-d030-11e4-83d4-eb0da9fc6465.png)
- [ ] Software/Hardware
  ![shno](https://cloud.githubusercontent.com/assets/1897053/6768424/13ea9f8a-d030-11e4-8390-00ba55e44781.png)
### PayPal Here App
- [x] Login
- [x] SMS
  ![smsyes](https://cloud.githubusercontent.com/assets/1897053/10724230/63818398-7b88-11e5-98d1-6e7c1a09f940.png)
- [x] Software/Hardware
  ![shyes](https://cloud.githubusercontent.com/assets/1897053/6768431/6b6133c8-d030-11e4-9b4c-9f6c8092cb61.png)
### API (PayPal in other apps)
- [x] Login
- [x] SMS
- [x] Software/Hardware

_Checking to see if this 2FA can be bypassed..._
### Main App
- [x] Login
- [x] SMS
  ![smsyes](https://cloud.githubusercontent.com/assets/1897053/6768456/9f299208-d031-11e4-904e-42acfee1f02a.png)
- [ ] Software/Hardware
  ![shno](https://cloud.githubusercontent.com/assets/1897053/6768499/40622e26-d034-11e4-9d43-534ecfaefc08.png)
### PayPal Here App
- [ ] Login
  ![no](https://cloud.githubusercontent.com/assets/1897053/6768518/93627eae-d035-11e4-9214-17754756be28.png)
- [ ] SMS
- [ ] Software/Hardware

_Checking to see if this 2FA can be bypassed..._
### API (PayPal in other apps)

? Login
? SMS
? Software/Hardware

_Checking to see if this 2FA can be bypassed..._
### Main App
- [ ] Login
  ![no](https://cloud.githubusercontent.com/assets/1897053/6768622/ce762c0a-d03c-11e4-9d05-6ad3f4dcf70b.png)
- [ ] SMS
- [ ] Software/Hardware
### PayPal Here App
- [ ] Login
  ![loginno](https://cloud.githubusercontent.com/assets/1897053/10725085/1232737e-7b8f-11e5-8203-50491b7bfa80.png)
- [ ] SMS
- [ ] Software/Hardware
### PayPal Here App

This is inherited from the Windows Phone PayPal Here App, as it is a universal app that works on all Windows platform devices.
# Help

Don't help me just yet... When I am done, I will need some help with wording and finding more information.

**Comment by jamcat22** [comment]
I'm going to lock this until I am done.

**Comment by Carlgo11** [comment]
Also as I've mentioned before, they only support TFA for 1 country as of right now. :disappointed:

**Comment by jamcat22** [comment]
I'll go ahead and unlock this now.
For now, just leave workarounds/bugs/loopholes out of the mix until PayPal replies.

**Comment by gberche-orange** [comment]
Note that Paypal France does not seem to support TFA: in the account preference, when choosing "security key" (Clé de sécurité), is says it is currently not available ("La clé de sécurité n'est pas disponible actuellement. Réessayez ultérieurement.")

**Comment by jamcat22** [comment]
@gberche-orange Thanks for letting me know. According to a tweet from PayPal, they only support certain countries (see #1072).

**Comment by abetancort** [comment]
**Paypal** as an online payment processor and bank and **ough to support 2FA internationally**.  
They took upon them to manage their customers' money and credit cards, and because of their own business choice, as thus _they have the fiduciary duty to employ the best known practices and maintain the highest standards to secure and maintain secured both online and offline their customers and any third party's financial information (current and past), money, accounts, and credit cards_. 
**It's not their choice and it should not be**. 

**We do need to keep the pressure up on them as they are getting too sloppy for their own good.**

**Comment by OLLI-S** [comment]
At the **German** website of PayPal only SMS authentication is available so I contacted the support and asked when 2FA by App will be available.
Here is their reply:
> PayPal arbeitet an einer entsprechenden Lösung, kann diese aber aktuell noch nicht zur Verfügung stellen.

Translated into English:
> PayPal is working on an appropriate solution, but can not currently make it available.

I asked when it will be available but received the answer that they can not tell me when it will be implemented.

**Comment by mxxcon** [comment]
@OLLI-S pretty much every single business will give you such a vague answer. Unfortunately, that's nothing unusual. :(

**Comment by OLLI-S** [comment]
@mxxcon I know, they won't tell us any details so they can't be nailed when they have a delay.

**Comment by joshsleeper** [comment]
Just an fyi, as of PayPal's policy changes today, I'm now seeing software token as an option when configuring my U.S. account MFA.
This was _not_ the case less than a week ago when I wrote their support contact about being frustrated over the same issue, so it's a pretty recent change.

**Comment by kmpoppe** [comment]
Will take a look at the German policy...

Josh Sleeper <notifications@github.com> schrieb am Do., 4. Apr. 2019, 15:00:

**Comment by OLLI-S** [comment]
I logged in at Paypay.com/de and went to the account settings.
Now I can add an authenticator app.

![PayPal](https://user-images.githubusercontent.com/8037790/55583568-754d1000-5722-11e9-8c19-0e4b40c2055a.png)

**Comment by kmpoppe** [comment]
Exactly what I was going to say, @OLLI-S ... FINALLY we can have a Software Token/Authenticator App on Paypal! Even in Germany ... *dances frantically*.
I'd love to know if there are other countries where this now works also?

**Comment by kmpoppe** [comment]
PayPal seems to be "fixed" as far as TOTP is concerned.
