### ISSUE TITLE
Summary 'please add/update site' requests

### ISSUE THREAD

**Issue by Carlgo11** [2factorauth/twofactorauth#1612]
##### Sites people have requested to be added on our list (along with issue number):
- [x] FreeDNS.afraid.org (#1338)
- [x] Merril Edge (#1426) `(Might be a part of Bank of America?)`
- [x] ElationEMR (#1474)
- [x] MercadoLivre Brasil (#1484)
- [x] Zurich Cantonal Bank (#1407)
- [x] Lufthansa (#1534)
- [x] Air France (#1534)
- [x] DB (#1534)
- [x] Citibank Australia (#166)
- [x] BMO Canada (#1422)
- [x] Abine (#1455)
- [x] IBM Bluemix (#1482)
- [x] Imperva (#1489)
- [x] WestJet (#1603)
- [x] Air Canada (#1603)
- [x] American Airlines (#1534)
- [x] Amtrak (#1534)
- [x] British Airlines (#1534)
- [x] Norwegian (#1534)
- [x] SAS (#1534)
- [x] EasyJet (#1534)
- [x] RyanAir (#1534)
- [x] Rogers Communications (#1603)
- [x] 007names (#1624)
- [x] Privacy.com (#1737)
- [x] Asana (#1669)
- [x] Discover Card (#1705)
##### Sites people have requested to update information about (along with issue number):
- [x] Skype (#1691)
- [x] Halifax (#1249)
- [x] Dashlane (#1613)
##### Gray area sites to be added (along with issue number):
- [x] QNAP (#1365)

_A list of PRs that were closed due to inactivity can be found using [this search string](https://github.com/2factorauth/twofactorauth/pulls?q=is%3Aclosed+label%3Abacklog+is%3Apr)._

**Comment by jdavis** [comment]
Adding https://privacy.com/

**Comment by Carlgo11** [comment]
@jdavis What's the status of privacy.com? Do they support TFA or not? If they do, is there any documentation page?

**Comment by jamcat22** [comment]
@carlgo11 They do, through software. They support Google Authenticator, and their doc page is at their [FAQ](https://privacy.com/faq).

**Comment by jamcat22** [comment]
All issues and PRs referenced by this issue have been closed. Closing to clean up issue list.
