### ISSUE TITLE
Awesome 1.0 Status

### ISSUE THREAD

**Issue by jdavis** [2factorauth/twofactorauth#320]
Overall status for Awesome 1.0 and who is working on it:
- [ ] [Search Bot](https://github.com/jdavis/twofactorauth/tree/bot) (@jdavis, ...) #269 
- [ ] [Stream Bot](https://github.com/jdavis/twofactorauth/tree/bot) (@jdavis, ...) #268 
- [ ] International Sections (@lbrunsmann, ...) #241 
- [x] Cleaner 2FA Providers (@smholloway, ...) #208

**Comment by smholloway** [comment]
PR #208 should work towards the `Cleaner 2FA Providers` todo. Did you have something else in mind?

If there's not one already, I'll work on a pull request to rework the main page with the columns that @mwww and I discussed (moving all 2fa providers into the custom column and keeping the columns more abstract, like SMS and TOTP).

**Comment by jdavis** [comment]
Awesome, I added you both.

**Comment by jdavis** [comment]
Does anyone think this is too overkill for getting the message across? xD

![screen shot 2014-03-23 at 2 00 59 pm](https://f.cloud.github.com/assets/157801/2494259/a3bdba52-b2bd-11e3-95da-3e28928ad797.png)

**Comment by StefanWallin** [comment]
I love that tweetview! It might be a bit overkill, but I like it!

**Comment by jeffgodwyll** [comment]
@jdavis What's the todo list about?

**Comment by rublon-mw** [comment]
@jdavis If you could display profile photos instead of names, I think that such a page could look better.

**Comment by jdavis** [comment]
@jeffgodwyll Back in #252 @StefanWallin had the idea of allowing people to make a list of the services they are using and track it while they add 2FA. I thought it was a really neat idea.

Lately though I've been thinking about if that's something we want to add though. While I like the idea, we might not want to add it to keep the site simple.

Also, @mwww, I totally agree that images would be great. I was showing profile images but the browser trying to load hundreds at once was pretty intense (naive implementation). If we do add profile images, we'll have to do some JavaScript stuff to lazily load them. It's definitely something I want to look into though.

**Comment by jdavis** [comment]
I'm going to take the todo list off of this version. We can add it later if people agree on it.

Still though, @StefanWallin, I like the idea, don't get me wrong =]
